services:
  db_dev:
    image: postgres:15
    environment:
      POSTGRES_DB: transfer-db
      POSTGRES_PASSWORD: secret
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
